[theme]
base            = "light"
primaryColor    = "#6159b7"
backgroundColor = "#f4f1eb"
secondaryBackgroundColor = "#ffffff"
textColor       = "#1e293b"
font            = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false